version: '3'

services:
  site:
    build: /
    volumes:
      - ./serv:/var/www/html
    ports:
      - "8082:80"
  nginx:
    image: nginx
    volumes:
      - ./serv:/var/www/html
      - ./nginx.conf:/etc/nginx/nginx.conf
    environment:
      - NGINX_PORT=80
    ports:
      - 80:80
    depends_on:
      - site
  phpmyadmin:
    container_name: phpmyadmin
    image: phpmyadmin/phpmyadmin
    restart: always
    environment:
        PMA_HOST: db
    ports:
        - 8000:80
    depends_on:
        - db
  db:
    image: mysql
    environment:
      MYSQL_ROOT_PASSWORD: password
    ports:
      - "3306:3306"
    volumes:
      - "./serv/init.sql:/docker-entrypoint-initdb.d/init.sql"